name: CI

on:
  pull_request:
    branches:
      - datalma-refacto-charts
      - main
  push:
    branches:
      - datalma-refacto-charts
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: Install dependencies (front)
        run: |
          cd ./front
          npm install

      - name: Build (front)
        run: |
          cd ./front
          NODE_OPTIONS="--max-old-space-size=8192" npm run build
